### ISSUE TITLE
error code 0x04: value is out of range or is not for the correct context when Activating credentials

### ISSUE THREAD

**Issue by GastonMeghi** [google/go-attestation#287]
When calling `ak.ActivateCredential(tpm, encryptedCredentials)` I get the error:
`error code 0x04: value is out of range or is not for the correct context `

I only get this on DELL devices (I just have one model of DELL so I can't assure that it happens in other devices) but I also tried it in a GCP instance and my Lenovo laptop and it worked, it's the DELL device that's having issues. 

I've read that this was solve on [#238](https://github.com/google/go-attestation/pull/238) but I still have issues with this.

Here is the version of go-attestation that I'm using:
`github.com/google/go-attestation v0.4.4-0.20220404204839-8820d49b18d9`

Thank you again for this great project!

**Comment by brandonweeks** [comment]
I suspect this might be caused by `f5d5601`. Could you please test with a version prior to that commit?

**Comment by GastonMeghi** [comment]
I've just tried a bunch of times with v0.4.3 and got exactly the same result. Is there any additional information that I can provide to make the debugging easier?

**Comment by GastonMeghi** [comment]
@brandonweeks I've been trying to see if I can solve the issue by myself without much luck. I've been tracing down the issue and it seems it's got something to do with the secret in the command: TPM2_ActivateCredential. But since this is encrypted I'm running out of ideas with my limited experience in the subject. Would you mind giving an insight on what could be wrong?

**Comment by twitchyliquid64** [comment]
If its just one dell device theres probably some invariant of how the ek template is stored thats not being considered, just like what was implemented for #238. Can you dump out your NVRAM values / indexes so we can poke around the EK template / whatever and see if theres anything we dont expect?

**Comment by GastonMeghi** [comment]
@twitchyliquid64 

Let me know if you need something else, but this what I could get:

```
tpm2_getcap handles-persistent
- 0x81000001
- 0x81000002
- 0x81010001
```

```
tpm2_readpublic -c 0x81010001
name: 000bcc45b71c4ecf2fdbc8669eb2ec1ee2fa27b661202b1c120025877942cccd6489
qualified name: 000b5e2d2ac27c133466cff942c5fdd90c228f5ed56b5d185fd3b8e9c505e2c0fe84
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|adminwithpolicy|restricted|decrypt
  raw: 0x300b2
type:
  value: rsa
  raw: 0x1
exponent: 0x0
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: 964c2581814fa2513dab805b2a3c4aeda19e98efed7a80a379480d1fe5016b41801f16124ded875767f0ac0b3e13e1378d6a863b896edbcecf6c9cc866b381924af9d03e230071fb9b54ee907cf27ebfe3953b71b3528542b95bd8713023f7568049d0d3d42e8e8e9d68c24feb33456d5c1136cada75334e5a81704e1382aa251f1008fc807ee5327da056abbaa2d73d3f6fee731fb6d2f0e08903b295c652f502f537c321b35a880ee6d6c9b09c14bbaf37bb687ffe0515c9684ffa8a3fd8b1940687b1a03631e2f7bdb580447b8ceb6451850e142ad0c1503efe2e1e9f4bb7ec6c9ea390b6f359b50a2fde772e1dae5f62f43fb86e50200815659eda7c2fa1
authorization policy: 837197674484b3f81a90cc8d46a5d724fd52d76e06520b64f2a1da1b331469aa
```

```
 tpm2_nvreadpublic
0x1410001:
  name: 000b9e380baaeeb236d46f699aa01c9163aa0c2d45de81fdf02b1b82fb3300ca9702
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: authwrite|nt=0x1|authread|no_da|orderly
    value: 0x14000406
  size: 16

0x1410002:
  name: 000b0c141eb1d038579d74843d9734ba22c2c540b8577177826419f4d30bab4c650a
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: authwrite|nt=0x1|authread|no_da|written
    value: 0x14000422
  size: 8

0x1410004:
  name: 000b866c4dee2765bcf46fd56dc1f297b1d4e39e3e3bfd8d6731c62d4e447ce87b4b
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ownerwrite|ownerread|no_da|written
    value: 0x2000222
  size: 8

0x1820002:
  name: 000bbc81cc49fcf914969cd008c448190026174784f1b76cdb4471dfa6a18398aa27
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: authwrite|authread|no_da|written
    value: 0x4000422
  size: 8

0x1880001:
  name: 000bd5e41629f4d1ee7b318d4a3e7eae93b0d11e72ffe71e5478f11461c49fa2e6f2
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: policywrite|nt=0x1|writeall|ownerread|authread|written
    value: 0x28100620
  size: 8
  authorization policy: 0C8DF0CF0169C38828C8FA4C0FF37A548C23C041AEECD2A12CA740D501D620B7

0x1880011:
  name: 000b51a55522eb40aa7f66605334f0814377c886126edb72391675ec8132258398ad
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ownerwrite|authwrite|ownerread|authread|written
    value: 0x6000620
  size: 32

0x1c00002:
  name: 000bec00c657a4e2724101954c2c9d51ddd45c825c3997ec0786c3afeb0f7fca3ec7
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1200762
  size: 1177

0x1c0000a:
  name: 000b2571404112c8aae1cde797c438d921093fc89b74d44564c25c296aaa26a6f041
  hash algorithm:
    friendly: sha256
    value: 0xB
  attributes:
    friendly: ppwrite|writedefine|ppread|ownerread|authread|no_da|written|platformcreate
    value: 0x1200762
  size: 781

```

I checked the EK template and it seems to be the standard one.

Thank you a lot for your help!
